### ISSUE TITLE
Extension marked as malware and cannot remove?

### ISSUE THREAD

**Issue by JrdnRgrs** [Saketkesar/Rewardsleet#1]
My browser is showing this extension as malware. While i'm sure that it is because of the autoclicking and what the extension itself does, I am a little disturbed that the extension keeps installing itself everytime i restart the browser when it is removed.

Unless the creator of this extension can explain themselves/how to remove the extension, I would avoid this (even though the utility of it is nice..)

**Comment by Saketkesar** [comment]
Hello,

I completely understand your concern regarding the recurring installation of the extension even after removal. I apologize for any inconvenience this has caused. While the utility of the extension may seem beneficial, I understand your apprehension and need for clarification.

As the creator of the extension, I take full responsibility for the issues you've encountered. I would like to provide you with detailed instructions on how to permanently remove the extension from your browser.

Please follow these steps:

Go to your browser's settings.
Navigate to the extensions or add-ons section.
Find the specific extension, and select the option to remove or delete it.
If the extension continues to reinstall itself, please consider resetting your browser to its default settings.
I sincerely apologize for any inconvenience this has caused you and assure you that I am actively working on rectifying these issues. If you have any further questions or concerns, please don't hesitate to reach out to me directly.
Rest assured, the extension is 100% safe.

Thank you for bringing this to my attention.
